import { ClerkProvider } from "@clerk/nextjs";
import { AuthProvider } from "@/context/AuthContext";
import Navbar from "./components/layout/Navbar";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`bg-gray-50 ${geistSans.variable} ${geistMono.variable}`}
          >
          <AuthProvider>
            <Navbar />
            <main className="max-w-6xl mx-auto">{children}</main>
          </AuthProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
